export const langs = {
  uz: {
    dashboard: "Dashboard",
    contacts: "Kontaktlar",
    debts: "Qarzlar",
    tasks: "Vazifalar",
    payments: "To'lovlar",
    reports: "Hisobotlar",
    search: "Ism, telefon, qarz bo'yicha qidirish...",
    addContact: "+ Kontakt qo'shish",
    addDebt: "+ Qarz qo'shish",
    save: "Saqlash",
    cancel: "Bekor",
    delete: "O'chir",
    close: "Yopish",
    givenDebt: "Berilgan qarz",
    takeDebt: "Olish kerak",
    overdueDebtsTitle: "Kechikkan qarzlar",
    pendingTasks: "Bajarilmagan vazifalar",
    unit: "ta",
    currency: "so'm",
    todayPayments: "Bugungi to'lovlar",
    noPaymentsToday: "Bugun to'lov yo'q",
    noOverdueDebts: "Kechikkan qarz yo'q",
    recentDebts: "Oxirgi qarzlar",
    colPerson: "Odam",
    colAmount: "Summa",
    colDate: "Sana",
    colDueDate: "Muddat",
    colRemaining: "Qoldiq",
    newContact: "Yangi kontakt",
    name: "Ism",
    phone: "Telefon",
    telegram: "Telegram",
    note: "Izoh",
    nameRequired: "Ism kiriting",
    noContacts: "Hali kontakt yo'q. Birinchisini qo'shing!",
    newDebt: "Yangi qarz",
    selectContact: "Kontakt tanlang...",
    debtType: "Turi",
    menBerdim: "Men berdim",
    mengaBerishdi: "Menga berishdi",
    amount: "Summa",
    currencyVallyuta: "Valyuta",
    givenDate: "Berilgan sana",
    returnDate: "Qaytarish muddati",
    all: "Barchasi",
    active: "Aktiv",
    overdue: "Kechikkan",
    closed: "Yopilgan",
    selectContactAlert: "Kontakt tanlang",
    enterAmountAlert: "Summa kiriting",
    firstAddContact: "Avval kontakt qo'shing!",
    noDebts: "qarz yo'q",
    given: "Men berdim",
    taken: "Menga berishdi",
    addTask: "+ Vazifa qo'shish",
    newTask: "Yangi vazifa",
    taskTitle: "Vazifa nomi",
    priority: "Muhimlik",
    high: "Muhim",
    medium: "O'rta",
    low: "Past",
    linkToDebt: "Qarzga bog'lash (ixtiyoriy)",
    noLink: "Bog'lamaslik",
    pending: "Bajarilmagan",
    done: "Bajarilgan",
    noTasks: "Vazifa yo'q.",
    linkedToDebt: "Qarzga bog'liq",
    enterTaskTitle: "Vazifa nomini kiriting",
    addPayment: "+ To'lov qo'shish",
    newPayment: "Yangi to'lov",
    selectDebt: "Qarzni tanlang",
    amountPaid: "To'langan summa",
    remaining: "Qoldiq",
    left: "qoldi",
    noPayments: "To'lovlar yo'q.",
    addDebtFirst: "Avval qarz qo'shing!",
    errorSelectDebt: "Qarz tanlang",
    errorEnterAmount: "Summa kiriting",
    debt: "Qarz",
    person: "Odam",
    csvExport: "CSV Eksport",
    totalGiven: "Jami berilgan",
    totalTaken: "Jami olingan",
    totalPaid: "Jami to'langan",
    contactsCount: "Kontaktlar",
    debtStatus: "Qarz holati",
    topDebtors: "Eng ko'p qarz bo'lganlar",
    peopleCount: "ta odam",
    itemsCount: "ta",
    noData: "Ma'lumot yo'q",
    currencyName: "so'm",
  },
  ru: {
    dashboard: "Главная",
    contacts: "Контакты",
    debts: "Долги",
    tasks: "Задачи",
    payments: "Платежи",
    reports: "Отчёты",
    search: "Поиск по имени, телефону...",
    addContact: "+ Добавить контакт",
    addDebt: "+ Добавить долг",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    close: "Закрыть",
    givenDebt: "Кредит выдан",
    takeDebt: "Дебиторка",
    overdueDebtsTitle: "Просроченные долги",
    pendingTasks: "Незавершенные задачи",
    unit: "шт",
    currency: "сум",
    todayPayments: "Платежи на сегодня",
    noPaymentsToday: "Сегодня платежей нет",
    noOverdueDebts: "Просроченных долгов нет",
    recentDebts: "Последние долги",
    colPerson: "Лицо",
    colAmount: "Сумма",
    colDate: "Дата",
    colDueDate: "Срок",
    colRemaining: "Остаток",
    newContact: "Новый контакт",
    name: "Имя",
    phone: "Телефон",
    telegram: "Телеграм",
    note: "Примечание",
    nameRequired: "Введите имя",
    noContacts: "Контактов пока нет. Добавьте первый!",
    newDebt: "Новый долг",
    selectContact: "Выберите контакт...",
    debtType: "Тип",
    menBerdim: "Я дал",
    mengaBerishdi: "Мне дали",
    amount: "Сумма",
    currencyVallyuta: "Валюта",
    givenDate: "Дата выдачи",
    returnDate: "Срок возврата",
    all: "Все",
    active: "Активные",
    overdue: "Просроченные",
    closed: "Закрытые",
    selectContactAlert: "Выберите контакт",
    enterAmountAlert: "Введите сумму",
    firstAddContact: "Сначала добавьте контакт!",
    noDebts: "нет долгов",
    given: "Я дал",
    taken: "Мне дали",
    addTask: "+ Добавить задачу",
    newTask: "Новая задача",
    taskTitle: "Название задачи",
    priority: "Приоритет",
    high: "Важно",
    medium: "Средне",
    low: "Низкий",
    linkToDebt: "Связать с долгом (опционально)",
    noLink: "Не связывать",
    pending: "Невыполненные",
    done: "Выполненные",
    noTasks: "Задач нет.",
    linkedToDebt: "Связано с долгом",
    enterTaskTitle: "Введите название задачи",
    addPayment: "+ Добавить платеж",
    newPayment: "Новый платеж",
    selectDebt: "Выберите долг",
    amountPaid: "Оплаченная сумма",
    remaining: "Остаток",
    left: "осталось",
    noPayments: "Платежей нет.",
    addDebtFirst: "Сначала добавьте долг!",
    errorSelectDebt: "Выберите долг",
    errorEnterAmount: "Введите сумму",
    debt: "Долг",
    person: "Лицо",
    csvExport: "Экспорт CSV",
    totalGiven: "Всего дано",
    totalTaken: "Всего взято",
    totalPaid: "Всего оплачено",
    contactsCount: "Контакты",
    debtStatus: "Статус долгов",
    topDebtors: "Топ должников",
    peopleCount: "чел.",
    itemsCount: "шт.",
    noData: "Нет данных",
    currencyName: "сум",
    colName: "Имя",
  },
  en: {
    dashboard: "Dashboard",
    contacts: "Contacts",
    debts: "Debts",
    search: "Search by name, phone...",
    addContact: "+ Add Contact",
    addDebt: "+ Add Debt",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    close: "Close",
    givenDebt: "Given debt",
    takeDebt: "Owed to me",
    overdueDebtsTitle: "Late debts",
    pendingTasks: "Unfinished tasks",
    unit: "pcs",
    currency: "UZS",
    todayPayments: "Today's Payments",
    noPaymentsToday: "No payments for today",
    noOverdueDebts: "No overdue debts",
    recentDebts: "Recent Debts",
    colPerson: "Person",
    colAmount: "Amount",
    colDate: "Date",
    colDueDate: "Due Date",
    colRemaining: "Remaining",
    newContact: "New Contact",
    name: "Name",
    phone: "Phone",
    telegram: "Telegram",
    nameRequired: "Enter a name",
    noContacts: "No contacts yet. Add the first one!",
    newDebt: "New Debt",
    selectContact: "Select contact...",
    debtType: "Type",
    menBerdim: "I gave",
    mengaBerishdi: "I took",
    amount: "Amount",
    currencyVallyuta: "Currency",
    givenDate: "Given date",
    returnDate: "Due date",
    all: "All",
    active: "Active",
    overdue: "Overdue",
    closed: "Closed",
    selectContactAlert: "Select a contact",
    enterAmountAlert: "Enter amount",
    firstAddContact: "Add a contact first!",
    noDebts: "no debts",
    given: "I gave",
    taken: "I took",
    tasks: "Tasks",
    addTask: "+ Add Task",
    newTask: "New Task",
    taskTitle: "Task Title",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    linkToDebt: "Link to debt (optional)",
    noLink: "Do not link",
    pending: "Pending",
    done: "Done",
    noTasks: "No tasks.",
    linkedToDebt: "Linked to debt",
    enterTaskTitle: "Enter task title",
    payments: "Payments",
    addPayment: "+ Add Payment",
    newPayment: "New Payment",
    selectDebt: "Select Debt",
    amountPaid: "Amount Paid",
    note: "Note",
    remaining: "Remaining",
    left: "left",
    noPayments: "No payments.",
    addDebtFirst: "Add a debt first!",
    errorSelectDebt: "Select a debt",
    errorEnterAmount: "Enter amount",
    debt: "Debt",
    person: "Person",
    reports: "Reports",
    csvExport: "CSV Export",
    totalGiven: "Total Given",
    totalTaken: "Total Taken",
    totalPaid: "Total Paid",
    contactsCount: "Contacts",
    debtStatus: "Debt Status",
    topDebtors: "Top Debtors",
    peopleCount: "people",
    itemsCount: "items",
    noData: "No data",
    currencyName: "sum",
  },
};
