export const langs = {
  uz: {
    personalCRM: "Shaxsiy CRM",
    dashboard: "Dashboard - qarzlar",
    contacts: "Kontaktlar",
    debts: "Qarzlar",
    tasks: "To-do list",
    payments: "To'lovlar",
    reports: "Hisobotlar",
    search: "Ism, telefon, qarz bo'yicha qidirish...",
    save: "Saqlash",
    cancel: "Bekor qilish",
    delete: "O'chir",
    remove: "O'chir",
    edit: "Tahrirlash",
    close: "Yopish",
    all: "Barchasi",
    noData: "Ma'lumot yo'q",
    unit: "ta",
    itemsCount: "ta",
    peopleCount: "ta odam",
    currency: "so'm",
    currencyName: "so'm",

    addContact: "+ Kontakt qo'shish",
    newContact: "Yangi kontakt",
    name: "Ism",
    phone: "Telefon",
    telegram: "Telegram",
    nameRequired: "Ism kiriting",
    noContacts: "Hali kontakt yo'q. Birinchisini qo'shing!",
    contactsCount: "Kontaktlar",

    addDebt: "+ Qarz qo'shish",
    newDebt: "Yangi qarz",
    selectContact: "Kontakt tanlang...",
    debtType: "Turi",
    menBerdim: "Men berdim",
    mengaBerishdi: "Menga berishdi",
    given: "Men berdim",
    taken: "Menga berishdi",
    givenDebt: "Berilgan qarz",
    takeDebt: "Olish kerak",
    amount: "Summa",
    currencyVallyuta: "Valyuta",
    givenDate: "Berilgan sana",
    returnDate: "Qaytarish muddati",
    active: "Aktiv",
    overdue: "Kechikkan",
    closed: "Yopilgan",
    overdueDebtsTitle: "Kechikkan qarzlar",
    noOverdueDebts: "Kechikkan qarz yo'q",
    recentDebts: "Oxirgi qarzlar",
    selectContactAlert: "Kontakt tanlang",
    enterAmountAlert: "Summa kiriting",
    firstAddContact: "Avval kontakt qo'shing!",
    noDebts: "Qarz yo'q",
    debtStatus: "Qarz holati",
    topDebtors: "Eng ko'p qarz bo'lganlar",

    addPayment: "To'lov qo'shish",
    newPayment: "Yangi to'lov",
    dailyPayment: "Kundalik to'lov",
    newDailyPayment: "Yangi kundalik to'lov",
    paymentType: "To'lov turi",
    dailyPaymentHint: "To'lov turi",
    debt: "Qarz",
    selectDebt: "Qarzni tanlang",
    addDebtFirst: "Avval qarz qo'shishingiz kerak",
    remaining: "Qoldiq",
    left: "qoldi",
    amountPaid: "To'langan summa",
    colDate: "Sana",
    colPerson: "Odam",
    colAmount: "Summa",
    colDueDate: "Muddat",
    colRemaining: "Qoldiq",
    person: "Kimga/Nima uchun",
    note: "Izoh",
    noPayments: "To'lovlar yo'q.",
    todayPayments: "Bugungi to'lovlar",
    noPaymentsToday: "Bugun to'lov yo'q",
    errorSelectDebt: "Iltimos, qarzni tanlang",
    errorEnterAmount: "Iltimos, summani kiriting",
    totalPaid: "Jami to'langan",
    totalGiven: "Jami berilgan",
    totalTaken: "Jami olingan",

    addTask: "+ Vazifa qo'shish",
    newTask: "Yangi vazifa",
    taskTitle: "Vazifa nomi",
    priority: "Muhimlik",
    high: "Muhim",
    medium: "O'rta",
    low: "Past",
    linkToDebt: "Qarzga bog'lash (ixtiyoriy)",
    noLink: "Bog'lamaslik",
    pending: "Bajarilmagan",
    done: "Bajarilgan",
    noTasks: "Vazifa yo'q.",
    pendingTasks: "Bajarilmagan vazifalar",
    linkedToDebt: "Qarzga bog'liq",
    enterTaskTitle: "Vazifa nomini kiriting",
    todoType: "Vazifa turini tanlash",
    task: "To-do list",
    personal: "Shaxsiy",
    market: "Bozor",
    meeting: "Uchrashuv",
    payment: "To'lov",

    csvExport: "CSV Eksport",
  },
  ru: {
    personalCRM: "Персональная CRM",
    dashboard: "Главная - долги",
    contacts: "Контакты",
    debts: "Долги",
    tasks: "Задачи",
    payments: "Платежи",
    reports: "Отчёты",
    search: "Поиск по имени, телефону...",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    remove: "Удалить",
    edit: "Редактировать",
    close: "Закрыть",
    all: "Все",
    noData: "Нет данных",
    unit: "шт",
    itemsCount: "шт.",
    peopleCount: "чел.",
    currency: "сум",
    currencyName: "сум",

    addContact: "+ Добавить контакт",
    newContact: "Новый контакт",
    name: "Имя",
    phone: "Телефон",
    telegram: "Телеграм",
    nameRequired: "Введите имя",
    noContacts: "Контактов пока нет. Добавьте первый!",
    contactsCount: "Контакты",

    addDebt: "+ Добавить долг",
    newDebt: "Новый долг",
    selectContact: "Выберите контакт...",
    debtType: "Тип",
    menBerdim: "Я дал",
    mengaBerishdi: "Мне дали",
    given: "Я дал",
    taken: "Мне дали",
    givenDebt: "Кредит выдан",
    takeDebt: "Дебиторка",
    amount: "Сумма",
    currencyVallyuta: "Валюта",
    givenDate: "Дата выдачи",
    returnDate: "Срок возврата",
    active: "Активные",
    overdue: "Просроченные",
    closed: "Закрытые",
    overdueDebtsTitle: "Просроченные долги",
    noOverdueDebts: "Просроченных долгов нет",
    recentDebts: "Последние долги",
    selectContactAlert: "Выберите контакт",
    enterAmountAlert: "Введите сумму",
    firstAddContact: "Сначала добавьте контакт!",
    noDebts: "Нет долгов",
    debtStatus: "Статус долгов",
    topDebtors: "Топ должников",

    addPayment: "Добавить платеж",
    newPayment: "Новый платеж",
    dailyPayment: "Ежедневный платеж",
    newDailyPayment: "Новый ежедневный платеж",
    paymentType: "Тип платежа",
    dailyPaymentHint: "Тип платежа",
    debt: "Долг",
    selectDebt: "Выберите долг",
    addDebtFirst: "Сначала добавьте долг!",
    remaining: "Остаток",
    left: "осталось",
    amountPaid: "Оплаченная сумма",
    colDate: "Дата",
    colPerson: "Лицо",
    colAmount: "Сумма",
    colDueDate: "Срок",
    colRemaining: "Остаток",
    person: "Кому/За что",
    note: "Примечание",
    noPayments: "Платежей нет.",
    todayPayments: "Платежи на сегодня",
    noPaymentsToday: "Сегодня платежей нет",
    errorSelectDebt: "Выберите долг",
    errorEnterAmount: "Введите сумму",
    totalPaid: "Всего оплачено",
    totalGiven: "Всего дано",
    totalTaken: "Всего взято",

    addTask: "+ Добавить задачу",
    newTask: "Новая задача",
    taskTitle: "Название задачи",
    priority: "Приоритет",
    high: "Важно",
    medium: "Средне",
    low: "Низкий",
    linkToDebt: "Связать с долгом (опционально)",
    noLink: "Не связывать",
    pending: "Невыполненные",
    done: "Выполненные",
    noTasks: "Задач нет.",
    pendingTasks: "Незавершенные задачи",
    linkedToDebt: "Связано с долгом",
    enterTaskTitle: "Введите название задачи",
    todoType: "Выберите тип задачи",
    task: "Задачи",
    personal: "Личное",
    market: "Рынок",
    meeting: "Встреча",
    payment: "Оплата",

    csvExport: "Экспорт CSV",
  },
  en: {
    personalCRM: "Personal CRM",
    dashboard: "Dashboard - debts",
    contacts: "Contacts",
    debts: "Debts",
    tasks: "To-do list",
    payments: "Payments",
    reports: "Reports",
    search: "Search by name, phone...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    remove: "Delete",
    edit: "Edit",
    close: "Close",
    all: "All",
    noData: "No data",
    unit: "pcs",
    itemsCount: "items",
    peopleCount: "people",
    currency: "UZS",
    currencyName: "sum",

    addContact: "+ Add Contact",
    newContact: "New Contact",
    name: "Name",
    phone: "Phone",
    telegram: "Telegram",
    nameRequired: "Enter a name",
    noContacts: "No contacts yet. Add the first one!",
    contactsCount: "Contacts",

    addDebt: "+ Add Debt",
    newDebt: "New Debt",
    selectContact: "Select contact...",
    debtType: "Type",
    menBerdim: "I gave",
    mengaBerishdi: "I took",
    given: "I gave",
    taken: "I took",
    givenDebt: "Given debt",
    takeDebt: "Owed to me",
    amount: "Amount",
    currencyVallyuta: "Currency",
    givenDate: "Given date",
    returnDate: "Due date",
    active: "Active",
    overdue: "Overdue",
    closed: "Closed",
    overdueDebtsTitle: "Late debts",
    noOverdueDebts: "No overdue debts",
    recentDebts: "Recent Debts",
    selectContactAlert: "Select a contact",
    enterAmountAlert: "Enter amount",
    firstAddContact: "Add a contact first!",
    noDebts: "No debts",
    debtStatus: "Debt Status",
    topDebtors: "Top Debtors",

    addPayment: "Add Payment",
    newPayment: "New Payment",
    dailyPayment: "Daily Payment",
    newDailyPayment: "New Daily Payment",
    paymentType: "Payment Type",
    dailyPaymentHint: "Payment type",
    debt: "Debt",
    selectDebt: "Select Debt",
    addDebtFirst: "Add a debt first!",
    remaining: "Remaining",
    left: "left",
    amountPaid: "Amount Paid",
    colDate: "Date",
    colPerson: "Person",
    colAmount: "Amount",
    colDueDate: "Due Date",
    colRemaining: "Remaining",
    person: "Person",
    note: "Note",
    noPayments: "No payments.",
    todayPayments: "Today's Payments",
    noPaymentsToday: "No payments for today",
    errorSelectDebt: "Select a debt",
    errorEnterAmount: "Enter amount",
    totalPaid: "Total Paid",
    totalGiven: "Total Given",
    totalTaken: "Total Taken",

    addTask: "+ Add Task",
    newTask: "New Task",
    taskTitle: "Task Title",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    linkToDebt: "Link to debt (optional)",
    noLink: "Do not link",
    pending: "Pending",
    done: "Done",
    noTasks: "No tasks.",
    pendingTasks: "Unfinished tasks",
    linkedToDebt: "Linked to debt",
    enterTaskTitle: "Enter task title",
    todoType: "Select task type",
    task: "To-do list",
    personal: "Personal",
    market: "Market",
    meeting: "Meeting",
    payment: "Payment",

    csvExport: "CSV Export",
  },
};
